// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SreAgent.Repository;

#nullable disable

namespace SreAgent.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314110654_AddSessionTokenUsage")]
    partial class AddSessionTokenUsage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SreAgent.Repository.Entities.AgentRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("agent_name");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<double?>("Confidence")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("confidence");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<JsonDocument>("Finding")
                        .HasColumnType("jsonb")
                        .HasColumnName("finding");

                    b.Property<JsonDocument>("Input")
                        .HasColumnType("jsonb")
                        .HasColumnName("input");

                    b.Property<JsonDocument>("Output")
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("agent_runs", (string)null);
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.ApprovalRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_type");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tool_name");

                    b.HasKey("Id");

                    b.HasIndex("ToolName");

                    b.ToTable("approval_rules", (string)null);
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor");

                    b.Property<string>("ActorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_id");

                    b.Property<JsonDocument>("EventData")
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventDescription")
                        .HasColumnType("text")
                        .HasColumnName("event_description");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "OccurredAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.CheckpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("AgentState")
                        .HasColumnType("jsonb")
                        .HasColumnName("agent_state");

                    b.Property<string>("CheckpointName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("checkpoint_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("MessageIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("message_ids");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<JsonDocument>("SessionState")
                        .HasColumnType("jsonb")
                        .HasColumnName("session_state");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("step_number");

                    b.Property<string>("SystemMessage")
                        .HasColumnType("text")
                        .HasColumnName("system_message");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("checkpoints", (string)null);
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.DiagnosticDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LogTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("log_timestamp");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("SourceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<JsonDocument>("StructuredFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("structured_fields");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<Guid?>("ToolInvocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_invocation_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SessionId", "LogTimestamp");

                    b.HasIndex("SessionId", "Severity");

                    b.HasIndex("SessionId", "SourceType");

                    b.ToTable("diagnostic_data", (string)null);
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.InterventionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTime>("IntervenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("intervened_at");

                    b.Property<string>("IntervenedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("intervened_by");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("interventions", (string)null);
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.MessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EstimatedTokens")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_tokens");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<JsonDocument>("Parts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parts");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.SessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("AlertData")
                        .HasColumnType("jsonb")
                        .HasColumnName("alert_data");

                    b.Property<string>("AlertId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("alert_id");

                    b.Property<string>("AlertName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("alert_name");

                    b.Property<string>("AlertSeverity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alert_severity");

                    b.Property<string>("AlertSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alert_source");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<double?>("Confidence")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentAgentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_agent_id");

                    b.Property<int>("CurrentStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_step");

                    b.Property<JsonDocument>("Diagnosis")
                        .HasColumnType("jsonb")
                        .HasColumnName("diagnosis");

                    b.Property<string>("DiagnosisSummary")
                        .HasColumnType("text")
                        .HasColumnName("diagnosis_summary");

                    b.Property<JsonDocument>("ExecutionState")
                        .HasColumnType("jsonb")
                        .HasColumnName("execution_state");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("ServiceMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("service_metadata");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("service_name");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.ToolInvocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<string>("ApprovalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("approval_status");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<JsonDocument>("Parameters")
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<JsonDocument>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tool_name");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.ToTable("tool_invocations", (string)null);
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.AgentRunEntity", b =>
                {
                    b.HasOne("SreAgent.Repository.Entities.SessionEntity", "Session")
                        .WithMany("AgentRuns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.AuditLogEntity", b =>
                {
                    b.HasOne("SreAgent.Repository.Entities.SessionEntity", "Session")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.CheckpointEntity", b =>
                {
                    b.HasOne("SreAgent.Repository.Entities.SessionEntity", "Session")
                        .WithMany("Checkpoints")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.DiagnosticDataEntity", b =>
                {
                    b.HasOne("SreAgent.Repository.Entities.SessionEntity", "Session")
                        .WithMany("DiagnosticData")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.InterventionEntity", b =>
                {
                    b.HasOne("SreAgent.Repository.Entities.SessionEntity", "Session")
                        .WithMany("Interventions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.MessageEntity", b =>
                {
                    b.HasOne("SreAgent.Repository.Entities.SessionEntity", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.ToolInvocationEntity", b =>
                {
                    b.HasOne("SreAgent.Repository.Entities.AgentRunEntity", "AgentRun")
                        .WithMany("ToolInvocations")
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentRun");
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.AgentRunEntity", b =>
                {
                    b.Navigation("ToolInvocations");
                });

            modelBuilder.Entity("SreAgent.Repository.Entities.SessionEntity", b =>
                {
                    b.Navigation("AgentRuns");

                    b.Navigation("AuditLogs");

                    b.Navigation("Checkpoints");

                    b.Navigation("DiagnosticData");

                    b.Navigation("Interventions");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
